### ISSUE TITLE
Maybe some bugs

### ISSUE THREAD

**Issue by R-Ceph** [LanqingLi1993/FOCAL-ICLR#4]
It's very nice of you to make this project opensource, but there may be some bugs.

1.  After installation and run `python policy_train.py --gpu 0` as your suggestion, bugs come out because the env "sparse-point-robot" is not registered and "ENV" don't have the key value, if we print ENV.keys(), we can see:

dict_keys(['walker-rand-params', 'sparse-walker-rand-params'])

2. If we test the "walker_rand_params" env, a new bug would come out:

> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/home/hxu/anaconda3/envs/py37/lib/python3.7/multiprocessing/pool.py", line 121, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/hxu/anaconda3/envs/py37/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
>     return list(itertools.starmap(args[0], args[1]))
>   File "policy_train.py", line 37, in experiment
>     env = NormalizedBoxEnv(ENVS[variant['env_name']](**variant['env_params']))
>   File "/mnt/wdisk/wdspace/nov_work/FOCAL-ICLR/rlkit/envs/walker_rand_params_wrapper.py", line 41, in __init__
>     self.tasks = self.sample_tasks(n_tasks)
>   File "/mnt/wdisk/wdspace/nov_work/FOCAL-ICLR/rlkit/envs/walker_rand_params_wrapper.py", line 86, in sample_tasks
>     task_params = read_log_params("./data/walker_rand_params/goal_idx{i}/log.txt")
>   File "/mnt/wdisk/wdspace/nov_work/FOCAL-ICLR/rlkit/envs/walker_rand_params_wrapper.py", line 8, in read_log_params
>     with open(log_file) as f:
> FileNotFoundError: [Errno 2] No such file or directory: './data/walker_rand_params/goal_idx{i}/log.txt'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "policy_train.py", line 83, in <module>
>     main()
>   File "/home/hxu/anaconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/hxu/anaconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 1062, in main
>     rv = self.invoke(ctx)
>   File "/home/hxu/anaconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/hxu/anaconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 763, in invoke
>     return __callback(*args, **kwargs)
>   File "policy_train.py", line 76, in main
>     p.starmap(experiment, product([variant], [cfg], list(range(variant['env_params']['n_tasks']))))
>   File "/home/hxu/anaconda3/envs/py37/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
>     return self._map_async(func, iterable, starmapstar, chunksize).get()
>   File "/home/hxu/anaconda3/envs/py37/lib/python3.7/multiprocessing/pool.py", line 657, in get
>     raise self._value
> FileNotFoundError: [Errno 2] No such file or directory: './data/walker_rand_params/goal_idx{i}/log.txt'

in "FOCAL-ICLR/rlkit/envs/walker_rand_params_wrapper.py", line 86, in sample_tasks
    task_params = read_log_params("./data/walker_rand_params/**goal_idx{i}**/log.txt")
There may be some grammatical errors in this line.

**Comment by LanqingLi1993** [comment]
Thanks for providing the feedback. To answer your questions:

1. The registration code of gym environments is in /rlkit/envs/__init__.py. The logic is if you use MuJoCo 131, only walker-related envs will be registered (that's why you see dict_keys(['walker-rand-params', 'sparse-walker-rand-params'])). If you want to use other envs like Sparse-Point-Robot, use a new VERSION_NUM other than "mjpro131":

export MUJOCO_PY_MJPRO_PATH= ~/.mujoco/mjpro${VERSION_NUM}
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH: ~/.mujoco/mjpro${VERSION_NUM}/bin

2.  Yes you are correct, the grammatically correct code here should be "task_params = read_log_params("./data/walker_rand_params/goal_idx{}/log.txt".format(i))". I have updated the repo accordingly.

Let me know if you have further questions. Thanks.

**Comment by R-Ceph** [comment]
Many thanks for your reply, and it's very helpful!
But I still met some other problems in data generation and data collection in Multitask buffer.
1. In train.yaml "num_train_steps" is set to 5000, and every training task will end in 5000 steps (taking cheetah as an example). Should we change this param larger?
2. In rl_algorithm.py "def init_buffer" : the code tends to open file "./data/cheetah-vel/goal_idx*/trj_evalsample43_step600000.npy" (which don't exist in ./data) with line:
`train_trj_paths += glob.glob(os.path.join(self.data_dir, "goal_idx*", "trj_evalsample%d_step%d.npy" %(n, self.train_epoch)))`
and 
`eval_trj_paths += glob.glob(os.path.join(self.data_dir, "goal_idx*", "trj_evalsample%d_step%d.npy" %(n, self.eval_epoch)))`.
After running 'python policy_train.py --gpu 0', files like "trj_evalsample43_step4800.npy" are created, which contains 200 transitions starting with 4800th step.

In my opinion, in the data generation stage, policies are trained individually for each task and all the transitions should be recorded. So is 5000 steps too little for training?
And in the init_buffer func, all the transitions should be loaded. So codes in "init_buffer" may need to be corrected..

**Comment by LanqingLi1993** [comment]
Hi, for your questions:

1. Yes, 5000 was for the 2 point-robot envs, in which agent can learn expert policy within a few thousand steps. For more complex envs like cheetah or ant, it requires at least 10^5 - 10^6 to converge, so you should increase this number for data collection with SAC.

2. The code we gave here only loads trajectories at step 600000, this is for EXPERT LEVEL dataset we experimented in the paper. In principle after training the SAC agents, you will have a large number of trajectories starting from random and gradually reaches expert level (e.g. step 2000 to 5000 for point-robot). Therefore, how to initialize buffer depends on the quality and distribution of the dataset you want to collect for training/testing. In the FOCAL paper, for example,  we experimented with expert, mixed and random in Table 2&6 in the Appendix, which correponds to step = 600000, 200000-600000, 200000) on cheetah-vel.

Hope this helps. Let me know if you have further questions.

**Comment by R-Ceph** [comment]
Finally, successfully run your open source codes, thank you very much for your help! 
By the way, your codes and paper are very clearly organized and easy to understand, I appreciate them very much!

**Comment by R-Ceph** [comment]
Hi Dr. Li, sorry to bother you again, but I met some questions when reproducing your work:
1. In table 3: there are "1000" steps in each trajectory for Half-Cheetah-Vel Dataset, but there would be 200 in practice?
2. How many steps in Fig.3 to eval Half-Cheetah-Vel and Half-Cheetah-Dir tasks? I  guess the answer is 200, but in config files, it's set to 600, which puzzles me.
3. Would you like to provide the scores of each expert data set used in Fig1? In the Cheetah-Vel environment, I used the data generated by the expert policy(which is generated by Meta-Q-Learning Algo) with a score of -30, but the score obtained by the focal algorithm is only about -170, which is lower than your result.

**Comment by LanqingLi1993** [comment]
Hi, for your questions:

1. "1000" steps in table 3 corresponds to the "trajectory length", which means each offline trajectory/episode lasts 1000 steps when collected. 200 in the config or the "maximum episode length" in table 4 was used mainly for evaluation, which means the episode terminates after 200 steps. The mismatch here is not ideal, I would recommend to set both of the parameters to 200, for example. However, I won't expect the result to be significantly different to what's reported in the paper, you are welcome to verify that.

2. No, we set num_steps_per_eval = 600 in the config, which means for every data point in Fig 3, we evaluate the average return over 600 transitions, which corresponds to 3 full episodes given each episode lasts 200 steps.

3. -30 is about right, I recall the data we used was about -30 to -50 in terms of return. The average testing return on Half-Cheetah-Vel in the camera-ready version is about -130 to -150, for which we set use_value_penalty=False. The result with value penalty should be lower than -150 I believe (check this earlier version: https://arxiv.org/pdf/2010.01112v1.pdf). So -170 is not a surprise if you didn't find the optimal hyperparameters. Also, I'm not sure if you took average over multiple seeds (usually you need > 3 random seeds), which should significantly lower the variation of the result.

**Comment by R-Ceph** [comment]
Thank you very much for your patient reply!
I solved problem 3 by using more noisy actions with MQL Algo as the former data was too singular... 

Best wishes,
Han
