### ISSUE TITLE
About the setting of baseline in the paper

### ISSUE THREAD

**Issue by MoreanP** [LanqingLi1993/FOCAL-ICLR#8]
Hello，after reading your paper, I am doing some related work recently.
But there are some problems about the experiment setup.
Whether the Brac algorithm is used for batch pearl in your paper?
Thanks

**Comment by LanqingLi1993** [comment]
Hi, 

Thanks for asking. We used Batch PEARL without BRAC in the main experiment (Figure 3). However, we did compare FOCAL with Batch PEARL with BRAC in Figure 4. In general, BRAC on Batch PEARL shows improvement, but still underperforms FOCAL.

Let me know if you have any other questions. @MoreanP

**Comment by MoreanP** [comment]
Thanks very much

**Comment by MoreanP** [comment]
> Hi,
> 
> Thanks for asking. We used Batch PEARL without BRAC in the main experiment (Figure 3). However, we did compare FOCAL with Batch PEARL with BRAC in Figure 4. In general, BRAC on Batch PEARL shows improvement, but still underperforms FOCAL.
> 
> Let me know if you have any other questions. @MoreanP

Thanks
